### ISSUE TITLE
Error in setwd(output_dir) : cannot change working directory Error: unable to load R code in package ‘MLWIC2’

### ISSUE THREAD

**Issue by ctorresuribe** [mikeyEcology/MLWIC2#10]
Hi, I am attempting to install MLWIC2, but I am having no luck when running the code to install it from devtools.

The errors seem to be related to the working directory, but I have not set the directory anywhere during the installation, so I am not sure if I need to set the wd first to a specific location before trying to run the code 'devtools::install_github("mikeyEcology/MLWIC2") '

Additonally, I don't know how to go about the second error where it says 'unable to load R code in package 'MLWIC2' ?

I am no developer, but have a good understanding of R and programming in general, but I am not sure why I can't install it, and how to fix the errors. I am an ecologist trying to give this package a go, and would love some guidance on this.

See screenshot of my screen below 

![Screenshot 2020-05-14 at 11 53 28](https://user-images.githubusercontent.com/57262600/81920563-a95b5b80-95d9-11ea-8a99-48787466d975.png)

**Comment by mikeyEcology** [comment]
There was an error. Please try to load it again.

**Comment by ctorresuribe** [comment]
Great! Thank you, it worked now!
