### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Chris-Has** [mikeyEcology/MLWIC2#13]
Hi there.
I'm attempting to retrain the species_model with my own data and i keep getting this error:

Original error:
Assign requires shapes of both tensors to match. lhs shape= [59] rhs shape= [1000]

I can classify the same data using the species_model.
It doesn't work with retrain=FALSE either

What would cause this?

Cheers
Chris

**Comment by mikeyEcology** [comment]
What did you put for `num_classes`?

**Comment by Chris-Has** [comment]
I've tried 59 and 58 for num_classes

**Comment by mikeyEcology** [comment]
Are you running in the console or in the Shiny App? Can you paste your code into this forum?

**Comment by Chris-Has** [comment]
[Error.txt](https://github.com/mikeyEcology/MLWIC2/files/4834484/Error.txt)

I'm using the console

**Comment by mikeyEcology** [comment]
what happens if you set `num_classes = 1000`. I know it's not right, but see if it works please.

**Comment by Chris-Has** [comment]
Oh yep that's working!
Any issue with running it with this setting?

**Comment by mikeyEcology** [comment]
It might take a little longer to train, but it will probably be negligible. Let me know if you get predictions outside of the classes that you used for training (if you have classes 0-10, and you get a classification of 12, this would be a problem).

**Comment by Chris-Has** [comment]
Okay, I only get the error when I retrain the species_model

**Comment by Chris-Has** [comment]
Thanks @mikeyEcology

**Comment by Chris-Has** [comment]
there were no problems with predictions outside of actual classes. Thanks
