### ISSUE TITLE
running MLWIC2::runShiny('setup') sometimes doesn't allow for designating python.exe location

### ISSUE THREAD

**Issue by Jonathan-Gore** [mikeyEcology/MLWIC2#2]
Ran the shiny app multiple times to no avail to start the setup process. Uninstalled and reinstalled every part of the process multiple times with no progress. Finally went to the command line instead and everything worked perfectly. Probably some simple miscommunication between the shiny interface and the R server.

**Comment by mikeyEcology** [comment]
Can you please clarify the problem you're having? It sound like you're using `runShiny('setup')` and it won't let you select your Python location?

**Comment by Jonathan-Gore** [comment]
Was more of a bug report than a specific problem I am having at the moment. Basically the Shiny interface for the Setup routine wasn't actually communicating any input to the R server/console. After uninstalling/reinstalling various parts of the process (python, conda, MLWIC, tensorflow, numpy, etc) I finally just used the CLI to set the python.exe location and it worked perfectly the first time. This is only for the Shiny interface for the setup() command. The interface seems to work for everything else.

**Comment by Jonathan-Gore** [comment]
I believe I figured out what happened. My python.exe was installed in my Users file. When the Shiny interface located my Users folder it recorded it as c:\Users\Jonathan\etc, \U is an escape character. When I changed the location of my python installation to just the c-drive the setup interface works again.
