### ISSUE TITLE
classify() 'guesses' returned as numeric values, with no translation table

### ISSUE THREAD

**Issue by git-og** [mikeyEcology/MLWIC2#21]
Both the outputs of classify(), MLWIC2_output.csv and model_predictions.txt, return numeric values, but I haven't found a table which translates these numeric values to species names. An example from MLWIC2_output.csv is:

guess1
--
18
11
11
11
24
24

What can we use to look up these values and know which species they refer to?

**Comment by git-og** [comment]
Thanks to all involved in the development of this package, it fills an important niche and will be very useful.

**Comment by mikeyEcology** [comment]
See this table: https://github.com/mikeyEcology/MLWIC2/blob/master/speciesIDcontains.csv

**Comment by git-og** [comment]
Great, thanks
