### ISSUE TITLE
Classify function did not run properly

### ISSUE THREAD

**Issue by varunkher23** [mikeyEcology/MLWIC2#27]
Getting the following error: 

run.py: error: unrecognized arguments: - Thar LTEO/Camera trapping/Auto-recognition/MLWIC2/MLWIC_examples-master/images - Thar LTEO/Camera trapping/Auto-recognition/MLWIC2/MLWIC_examples-master/image_labels.csv - Thar LTEO/Camera trapping/Auto-recognition/MLWIC2/MLWIC2_helper_files/model_predictions.txt
The classify function did not run properly.

on running:

classify(path_prefix = "D:/WII - Thar LTEO/Camera trapping/Auto-recognition/MLWIC2/MLWIC_examples-master/images", # this is the absolute path to the images. 
         data_info = "D:/WII - Thar LTEO/Camera trapping/Auto-recognition/MLWIC2/MLWIC_examples-master/image_labels.csv", # this is the location of the csv containing image information. It has Unix linebreaks and no headers.
         model_dir = "D:/WII - Thar LTEO/Camera trapping/Auto-recognition/MLWIC2/MLWIC2_helper_files", 
         python_loc = "C:/Users/varun/anaconda3/envs/r-reticulate", # the location of Python on your computer. 
         save_predictions = "model_predictions.txt", 
        os="Windows",output_location = "D:/WII - Thar LTEO/Camera trapping/Auto-recognition/MLWIC2/MLWIC_examples-master/",
        make_output = TRUE, 
        output_name = "MLWIC2_output.csv", 
        num_cores = 4 
)

This is while running the examples file. Any solutions? Thanks.

**Comment by mikeyEcology** [comment]
You have a space in your path.

**Comment by varunkher23** [comment]
Oops. This issue is cleared. But a new issue now:

Your `data_info` file exists: D:/WII-Thar_LTEO/Camera_trapping/Auto-recognition/MLWIC2/MLWIC_examples-master/image_labels.csv.
Your `path_prefix exists: D:/WII-Thar_LTEO/Camera_trapping/Auto-recognition/MLWIC2/MLWIC_examples-master/images.
You are running on a Windows computer.
Traceback (most recent call last):
  File "run.py", line 412, in <module>
    main()
  File "run.py", line 351, in main
    sess = tf.Session(config=tf.ConfigProto(
AttributeError: module 'tensorflow' has no attribute 'Session'
The classify function did not run properly.

**Comment by varunkher23** [comment]
The last issue got solved by uninstalling tensorflow v2 and installing tensorflow v1. The code worked on the example file. Trying on personal dataset now.
Thanks for your help
