### ISSUE TITLE
Confused about how to interpret output of empty_animal model

### ISSUE THREAD

**Issue by Jonathan-Gore** [mikeyEcology/MLWIC2#3]
I'm a little confused after successfully running empty_animal. Am I to correctly interpret answer = 0 means there were no animals detected?
[MLWIC2_output.xlsx](https://github.com/mikeyEcology/MLWIC2/files/4309468/MLWIC2_output.xlsx)

**Comment by mikeyEcology** [comment]
In this table, answer is (or at least should be) the value you supplied in your input file. `guess1` is the model's guess for what is in the image, where `0=no animal detected` and `1=animal detected`.
