### ISSUE TITLE
Training model with images not scaled to 256x256

### ISSUE THREAD

**Issue by Chris-Has** [mikeyEcology/MLWIC2#7]
Hi
I noticed in the readme it states that users have managed to train images without scaling down to 256x256 so I scaled some images to 512x512 but wasn't able to train a model.
Did these users make further adjustments to the python code or should this be possible using the package 'out of the box'?

Thanks
Chris

**Comment by mikeyEcology** [comment]
I don't think it would be possible out of the box because the function asks for 256x256 images. I think the folks that did this modified the functions. If you're interested, I can help you edit the scripts that would allow for more pixels in the images.

**Comment by Chris-Has** [comment]
Thanks @mikeyEcology, that would be fantastic!
Since I'm not well versed in python my attempts have been frugal.

**Comment by Chris-Has** [comment]
All I've done is returned back to MLWIC, not MLWIC2, and changed the load_size argument in train.py to [512,512] and it's training now.
I'm hoping that will actually be fine because the function already allows for the different image size the ResNet architecture uses of 224x224?

Side note:
For some reason, I have a lot of issues using MLWIC2, possibly due to using shared nodes (gpu memory allocation issues)

**Comment by mikeyEcology** [comment]
You could make the same modification in MLWIC2 in the `run.py` file. You would edit the `raw_size` argument at line 305. My concern, though, is that the function also crops the image to 254x254, so you might get really low accuracy unless all of your animals are right in the middle. You can also edit this in the next line with the `processed-size` argument, but I'm not  immediately sure if this will lead to errors down the line. 
I'm not sure why MLWIC2 would lead to GPU errors when MLWIC wouldn't. Are you setting `num_gpus` to the proper number? You also might need to change `num_cores` to be >1 for a gpu to work properly. You also might have to modify your conda environment to find your cuda installation.
